import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { clone, DEFAULT_RULES, PROFILES, scenario } from '../web/model.js';

const root = fileURLToPath(new URL('../', import.meta.url));
const server = spawn(process.execPath, ['server.mjs'], { cwd: root, env: { ...process.env, PORT: '0', HOST: '127.0.0.1' }, stdio: ['ignore', 'pipe', 'pipe'] });
let browser;
try {
  const port = await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(Error('Server startup timed out')), 10000);
    server.stdout.on('data', data => { const m = String(data).match(/port (\d+)/); if (m) { clearTimeout(timer); resolve(m[1]); } });
    server.on('error', reject); server.on('exit', code => { clearTimeout(timer); reject(Error(`Server exited: ${code}`)); });
  });
  const url = `http://127.0.0.1:${port}`;
  assert.equal((await fetch(url + '/missing')).status, 404);
  const executablePath = process.env.SHOT_BROWSER_PATH;
  browser = await chromium.launch({ headless: true, ...(executablePath ? { executablePath } : {}), args: ['--no-sandbox'] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(url);
  await page.locator('#average').waitFor();
  assert.equal(await page.title(), 'shot · 关卡体验实验室');
  assert.equal(await page.locator('#events tr').count(), 7);
  const initialAverage = await page.locator('#average').textContent();
  await page.locator('#unit').fill('30'); await page.locator('#unit').dispatchEvent('change');
  assert.equal(await page.locator('#average').textContent(), initialAverage);
  await page.locator('#unit').fill('0'); await page.locator('#unit').dispatchEvent('change');
  assert.equal(await page.locator('#unit').inputValue(), '30');
  assert.match(await page.locator('#status').textContent(), /必须/);
  await page.locator('#baseline').click();
  await page.locator('#profile').selectOption('casual');
  assert.notEqual(await page.locator('#average').textContent(), initialAverage);
  assert.ok(await page.locator('#baseline-label').isVisible());
  assert.match(await page.locator('#delta').textContent(), /与基线相比/);
  await page.locator('#add-event').click();
  assert.equal(await page.locator('#events tr').count(), 8);
  await page.locator('[name="name"]').fill('<script>shot-test</script>');
  await page.locator('[name="start"]').fill('1120.5');
  await page.locator('[name="duration"]').fill('60');
  await page.locator('#event-form button[type="submit"]').click();
  assert.equal(await page.locator('.event-name').last().textContent(), '<script>shot-test</script>');
  const beforeInvalid = await page.locator('#average').textContent();
  await page.locator('[name="start"]').fill('7200');
  await page.locator('#event-form').evaluate(form => form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })));
  assert.match(await page.locator('#form-error').textContent(), /7200/);
  assert.equal(await page.locator('#average').textContent(), beforeInvalid);
  await page.reload();
  assert.equal(await page.locator('#events tr').count(), 8);
  const importJSON = async (id, data) => {
    await page.locator(id).setInputFiles({ name: 'input.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) });
    await page.waitForFunction(id => document.querySelector(id).value === '', id);
  };
  await importJSON('#import-rules', { version: 1, name: 'bad' });
  assert.match(await page.locator('#status').textContent(), /导入失败/);
  assert.equal(await page.locator('#average').textContent(), beforeInvalid);
  const rules = clone(DEFAULT_RULES); rules.name = '测试导入规则'; rules.weights.base += 1;
  await importJSON('#import-rules', rules);
  assert.equal(await page.locator('#rule-name').textContent(), rules.name);
  assert.notEqual(await page.locator('#average').textContent(), beforeInvalid);
  await importJSON('#import-profile', PROFILES.expert);
  assert.equal(await page.locator('#profile').inputValue(), 'custom');
  await importJSON('#import-project', { version: 1, events: [], profile: PROFILES.balanced, rules: DEFAULT_RULES, unit: 5 });
  assert.equal(await page.locator('#events .empty').count(), 1);
  assert.ok(await page.locator('#event-form button[type="submit"]').isDisabled());
  await page.locator('#add-event').click();
  assert.equal(await page.locator('#events tr').count(), 1);
  await importJSON('#import-project', { version: 1, events: scenario('wrong-order'), profile: PROFILES.balanced, rules: DEFAULT_RULES, unit: 5 });
  assert.match(await page.locator('#diagnostics').textContent(), /机制知识不足/);
  await page.locator('#diagnostics [data-edit]').first().click();
  assert.equal(await page.locator('[name="name"]').inputValue(), '复杂解谜');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#export-project').click();
  const download = await downloadPromise;
  const exported = JSON.parse(await readFile(await download.path(), 'utf8'));
  assert.deepEqual(exported.events, scenario('wrong-order'));
  await mkdir(root + 'artifacts', { recursive: true });
  await page.screenshot({ path: root + 'artifacts/shot-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, 'Mobile page must not overflow horizontally');
  await page.screenshot({ path: root + 'artifacts/shot-mobile.png', fullPage: true });
  assert.deepEqual(errors, [], 'No uncaught browser errors');
  console.log('PASS: server, sampling, baseline, profiles, edit/save, invalid input, persistence, imports, export, diagnosis navigation and mobile layout');
} finally {
  await browser?.close(); server.kill('SIGTERM');
}
