import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { clone, DEFAULT_RULES, PROFILES, scenario } from '../web/model.js';
const root = fileURLToPath(new URL('../', import.meta.url));
const server = spawn(process.execPath, ['server.mjs'], { cwd: root, env: { ...process.env, PORT: '0', HOST: '127.0.0.1' }, stdio: ['ignore', 'pipe', 'pipe'] });
let browser;
try {
  const port = await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(Error('Server startup timed out')), 10000);
    server.stdout.on('data', data => { const m = String(data).match(/port (\d+)/); if (m) { clearTimeout(timer); resolve(m[1]); } });
    server.on('error', reject); server.on('exit', code => { clearTimeout(timer); reject(Error(`Server exited: ${code}`)); });
  });
  const url = `http://127.0.0.1:${port}`;
  assert.equal((await fetch(url + '/missing')).status, 404);
  browser = await chromium.launch({ headless: true, ...(process.env.SHOT_BROWSER_PATH ? { executablePath: process.env.SHOT_BROWSER_PATH } : {}), args: ['--no-sandbox'] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const run = async () => { await page.locator('#run-analysis').click(); assert.match(await page.locator('#analysis-state').textContent(), /分析已完成/); };
  const importJSON = async (id, data) => {
    await page.locator(id).setInputFiles({ name: 'input.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) });
    await page.waitForFunction(id => document.querySelector(id).value === '', id);
  };
  const addEvent = async () => {
    await page.locator('#timeline').scrollIntoViewIfNeeded();
    await page.locator('#timeline').evaluate(e => { e.scrollLeft = 0; e.scrollTop = 0; });
    const bounds = await page.locator('#time-grid').boundingBox();
    await page.mouse.click(bounds.x + 26, bounds.y + 154);
  };
  await page.goto(url);
  assert.equal(await page.title(), '我的第一次分析 · shot');
  assert.equal(await page.locator('#events tr').count(), 7);
  assert.equal(await page.locator('.controls select').count(), 3);
  assert.equal(await page.locator('#floating-config #plan-select').count(), 1);
  assert.equal(await page.locator('.app-content .plan-toolbar').count(), 0);
  assert.equal(await page.locator('.controls #import-rules').count(), 1);
  assert.equal(await page.locator('.controls #import-profile').count(), 1);
  assert.equal(await page.locator('#export-rules, #export-profile').count(), 0);
  assert.equal(await page.locator('#average').textContent(), '—');
  assert.equal(await page.locator('#analyze-current-only').isChecked(), false);
  await run(); const initial = await page.locator('#average').textContent();
  assert.equal(await page.locator('.timeline-actions, #scenario, #add-event').count(), 0);
  const settled = async () => page.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
  const keepPosition = async operation => {
    await page.evaluate(() => window.scrollTo(0, 800)); await settled();
    const before = await page.evaluate(() => window.scrollY);
    await operation(); await settled();
    assert.ok(Math.abs(await page.evaluate(() => window.scrollY) - before) <= 2, 'Configuration actions preserve viewport');
    const config = await page.locator('#floating-config').boundingBox();
    assert.ok(config.y >= 0 && config.y < 50, 'Configuration remains fixed in viewport');
  };
  await keepPosition(() => page.locator('#profile').selectOption('expert'));
  await keepPosition(() => importJSON('#import-rules', DEFAULT_RULES));
  await keepPosition(() => importJSON('#import-profile', PROFILES.balanced));
  await keepPosition(() => page.locator('#rules').selectOption('default'));
  await keepPosition(async () => { await page.locator('#unit').fill('10'); await page.locator('#unit').dispatchEvent('change'); });
  await keepPosition(run);
  await mkdir(root + 'artifacts', { recursive: true });
  await page.locator('.chart-panel').scrollIntoViewIfNeeded();
  await page.screenshot({ path: root + 'artifacts/shot-floating-config.png' });

  await page.locator('#unit').fill('30'); await page.locator('#unit').dispatchEvent('change');
  assert.match(await page.locator('#analysis-state').textContent(), /上次结果/);
  assert.equal(await page.locator('#baseline').count(), 0);
  await run(); assert.equal(await page.locator('#average').textContent(), initial);
  await page.locator('#unit').fill('0'); await page.locator('#unit').dispatchEvent('change');
  assert.equal(await page.locator('#unit').inputValue(), '30');
  await page.locator('#profile').selectOption('casual');
  assert.equal(await page.locator('#average').textContent(), initial);
  await run(); assert.notEqual(await page.locator('#average').textContent(), initial);
  assert.equal(await page.locator('#plan-comparison input:checked').count(), 1);
  await addEvent(); await page.locator('[name="name"]').fill('<script>shot-test</script>');
  await page.locator('[name="start"]').fill('1120.5'); await page.locator('[name="duration"]').fill('60');
  await page.locator('#event-form button[type="submit"]').click();
  assert.equal(await page.locator('.event-name').last().textContent(), '<script>shot-test</script>');
  await run(); const beforeInvalid = await page.locator('#average').textContent();
  await page.locator('[name="start"]').fill('7200');
  await page.locator('#event-form').evaluate(f => f.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })));
  assert.match(await page.locator('#form-error').textContent(), /7200/);
  assert.equal(await page.locator('#average').textContent(), beforeInvalid);
  await page.reload(); assert.equal(await page.locator('#events tr').count(), 8);
  assert.equal(await page.locator('#average').textContent(), beforeInvalid); await run();
  await importJSON('#import-rules', { version: 1, name: 'bad' });
  assert.match(await page.locator('#status').textContent(), /导入失败/);
  assert.equal(await page.locator('#average').textContent(), beforeInvalid);
  const rules = clone(DEFAULT_RULES); rules.name = '测试导入规则'; rules.weights.base += 1;
  await importJSON('#import-rules', rules);
  assert.equal(await page.locator('#rules option:checked').textContent(), rules.name);
  assert.equal(await page.locator('#average').textContent(), beforeInvalid);
  await run(); assert.notEqual(await page.locator('#average').textContent(), beforeInvalid);
  await importJSON('#import-profile', PROFILES.expert);
  assert.equal(await page.locator('#profile option:checked').textContent(), PROFILES.expert.name);
  await importJSON('#import-project', { version: 1, events: scenario('wrong-order'), profile: PROFILES.balanced, rules: DEFAULT_RULES, unit: 5 });
  await run(); assert.match(await page.locator('#diagnostics').textContent(), /机制知识不足/);
  await page.locator('#diagnostics [data-edit]').first().click();
  assert.equal(await page.locator('[name="name"]').inputValue(), '复杂解谜');
  const exportedPromise = page.waitForEvent('download'); await page.locator('#export-project').click();
  const exported = JSON.parse(await readFile(await (await exportedPromise).path(), 'utf8'));
  assert.deepEqual(exported.events, scenario('wrong-order'));
  // Independent copied/blank plans, comparison visibility, stale snapshots and reload.
  const originalPlan = await page.locator('#plan-select').inputValue();
  const originalAverage = await page.locator('#average').textContent();
  await page.locator('#copy-plan').click();
  const copiedPlan = await page.locator('#plan-select').inputValue();
  assert.notEqual(copiedPlan, originalPlan);
  assert.equal(await page.locator('#events tr').count(), 7);
  assert.equal(await page.locator('#average').textContent(), '—');
  await page.locator('#plan-name').fill('调整方案'); await page.locator('#plan-name').dispatchEvent('change');
  await page.locator('#profile').selectOption('expert');
  await page.locator('.grid-event').first().click();
  await page.locator('[name="name"]').fill('只修改副本'); await page.locator('#save-event').click();
  await run();
  assert.equal(await page.locator('#chart polyline').count(), 8);
  await page.locator(`#plan-comparison [data-compare-plan="${originalPlan}"]`).uncheck();
  assert.equal(await page.locator('#chart polyline').count(), 4);
  await page.locator(`#plan-comparison [data-compare-plan="${originalPlan}"]`).check();
  await page.locator('#unit').fill('10'); await page.locator('#unit').dispatchEvent('change');
  assert.match(await page.locator('#plan-comparison').textContent(), /待重新分析/);
  await page.reload();
  assert.equal(await page.locator('#plan-select').inputValue(), copiedPlan);
  assert.equal(await page.locator('#chart polyline').count(), 8);
  assert.match(await page.locator('#plan-comparison').textContent(), /待重新分析/);
  await page.locator('#plan-select').selectOption(originalPlan);
  assert.equal(await page.locator('#average').textContent(), originalAverage);
  assert.equal(await page.locator('[name="name"]').inputValue(), '复杂解谜');
  assert.equal(await page.locator('#unit').inputValue(), '5');
  await page.locator('#new-plan').click();
  assert.equal(await page.locator('#events .empty').count(), 1);
  assert.equal(await page.locator('#average').textContent(), '—');
  await page.locator('#plan-select').selectOption(originalPlan);
  await page.locator('#unit').fill('15'); await page.locator('#unit').dispatchEvent('change');
  await page.locator('#plan-select').selectOption(copiedPlan);
  await page.locator('#analyze-current-only').check(); await run();
  assert.match(await page.locator('#status').textContent(), /当前方案分析完成/);
  assert.match(await page.locator('#plan-comparison').textContent(), /待重新分析/);
  assert.match(await page.locator('#plan-comparison').textContent(), /未分析/);
  await page.locator('#analyze-current-only').uncheck(); await run();
  assert.match(await page.locator('#status').textContent(), /全部 3 个方案/);
  assert.doesNotMatch(await page.locator('#plan-comparison').textContent(), /待重新分析|未分析/);
  await page.reload();
  assert.equal(await page.locator('#analyze-current-only').isChecked(), false);
  assert.doesNotMatch(await page.locator('#plan-comparison').textContent(), /待重新分析|未分析/);
  await page.locator('#plan-select').selectOption(originalPlan);
  await page.locator('#unit').fill('5'); await page.locator('#unit').dispatchEvent('change'); await run();
  await page.locator('#session-title').fill('关卡 A'); await page.locator('#session-title').dispatchEvent('change');
  const first = await page.locator('.session-item.active').getAttribute('data-session');
  await page.locator('#new-session').click(); assert.equal(await page.locator('#events .empty').count(), 1);
  assert.equal(await page.locator('#average').textContent(), '—');
  await page.locator('#session-title').fill('关卡 B'); await page.locator('#session-title').dispatchEvent('change');
  const second = await page.locator('.session-item.active').getAttribute('data-session');
  // Imported options are reusable, while selection and results remain per session.
  await page.locator('#rules').selectOption({ label: rules.name });
  await addEvent(); await page.locator('[name="name"]').fill('B 的独立事件');
  await page.locator('#event-form button[type="submit"]').click();
  await page.locator('#unit').fill('30'); await page.locator('#unit').dispatchEvent('change');
  await page.locator('#profile').selectOption('casual'); await run();
  await page.locator(`[data-session="${first}"]`).click();
  assert.equal(await page.locator('#events tr').count(), 7);
  assert.equal(await page.locator('#rules option:checked').textContent(), DEFAULT_RULES.name);
  assert.equal(await page.locator('#unit').inputValue(), '5'); assert.equal(await page.locator('#plan-select option').count(), 3);
  await page.locator(`[data-session="${second}"]`).click();
  assert.equal(await page.locator('.event-name').textContent(), 'B 的独立事件');
  assert.equal(await page.locator('#rules option:checked').textContent(), rules.name);
  assert.equal(await page.locator('#plan-select option').count(), 1);
  const selectedRule = await page.locator('#rules').inputValue();
  // Editor saves a separate catalog item without modifying a session selection.
  await page.locator('#open-rule-editor').click();
  assert.ok(await page.locator('#library-editor').isVisible());
  await page.locator('#library-json').fill('{invalid'); await page.locator('#library-save').click();
  assert.match(await page.locator('#library-error').textContent(), /保存失败/);
  const editedRule = clone(DEFAULT_RULES); editedRule.name = '编辑器规则'; editedRule.weights.base = 3;
  await page.locator('#library-json').fill(JSON.stringify(editedRule)); await page.locator('#library-save').click();
  assert.equal(await page.locator('#rules').inputValue(), selectedRule);
  const ruleDownloadPromise = page.waitForEvent('download'); await page.locator('#library-export').click();
  const exportedRule = JSON.parse(await readFile(await (await ruleDownloadPromise).path(), 'utf8'));
  assert.deepEqual(exportedRule, editedRule); await page.locator('#close-library-editor').click();
  await page.locator('#open-profile-editor').click();
  const editedProfile = { ...PROFILES.balanced, name: '测试玩家类型', skill: 2 };
  await page.locator('#library-json').fill(JSON.stringify(editedProfile)); await page.locator('#library-save').click();
  await mkdir(root + 'artifacts', { recursive: true });
  await page.locator('#library-editor').screenshot({ path: root + 'artifacts/shot-profile-editor.png' });
  await page.locator('#close-library-editor').click();
  await page.locator('#rules').selectOption({ label: editedRule.name });
  await page.locator('#profile').selectOption({ label: editedProfile.name }); await run();
  await page.reload();
  assert.equal(await page.locator('#session-title').inputValue(), '关卡 B');
  assert.equal(await page.locator('#rules option:checked').textContent(), editedRule.name);
  assert.equal(await page.locator('#profile option:checked').textContent(), editedProfile.name);
  assert.equal(await page.locator('.session-item').count(), 2);
  await page.locator(`[data-session="${first}"]`).click(); await run();
  await mkdir(root + 'artifacts', { recursive: true }); await page.evaluate(() => window.scrollTo(0, 0));
  await page.locator('.controls').screenshot({ path: root + 'artifacts/shot-session-config.png' });
  await page.screenshot({ path: root + 'artifacts/shot-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await page.locator('#sidebar-toggle').click();
  await page.locator(`[data-session="${second}"]`).click();
  assert.ok(await page.locator('#sidebar-backdrop').isHidden());
  assert.ok(await page.locator('#floating-config').isHidden());
  await page.evaluate(() => window.scrollTo(0, 300)); await settled();
  const mobileScroll = await page.evaluate(() => window.scrollY);
  await page.locator('#config-toggle').click();
  assert.ok(await page.locator('#floating-config').isVisible());
  await page.locator('#profile').selectOption('casual'); await settled();
  assert.ok(Math.abs(await page.evaluate(() => window.scrollY) - mobileScroll) <= 2);
  await page.locator('#config-toggle').click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
  await page.screenshot({ path: root + 'artifacts/shot-mobile.png', fullPage: true });
  assert.deepEqual(errors, []);
  const timelinePage = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
  timelinePage.on('pageerror', error => errors.push(error.message));
  await timelinePage.goto(url); await timelinePage.locator('#new-session').click();
  await timelinePage.locator('#timeline').scrollIntoViewIfNeeded();
  const coords = async (column, lane) => {
    const bounds = await timelinePage.locator('#time-grid').boundingBox();
    return { x: bounds.x + column * 52 + 26, y: bounds.y + lane * 44 + 22 };
  };
  let spot = await coords(2, 1); await timelinePage.mouse.click(spot.x, spot.y);
  assert.equal(await timelinePage.locator('[name="start"]').inputValue(), '10');
  assert.equal(await timelinePage.locator('#events .empty').count(), 1, 'Draft does not mutate the project');
  await timelinePage.locator('[name="name"]').fill('格子事件');
  await timelinePage.locator('#save-event').click();
  assert.equal(await timelinePage.locator('.grid-event').count(), 1);
  await timelinePage.locator('#timeline').scrollIntoViewIfNeeded();
  spot = await coords(2, 1); const destination = await coords(6, 2);
  await timelinePage.mouse.move(spot.x, spot.y); await timelinePage.mouse.down();
  await timelinePage.mouse.move(destination.x, destination.y, { steps: 12 }); await timelinePage.mouse.up();
  assert.equal(await timelinePage.locator('[name="start"]').inputValue(), '30');
  assert.equal(await timelinePage.locator('[name="duration"]').inputValue(), '5');
  // Right-click actions preserve timing and create independent copies/templates.
  await timelinePage.mouse.click(destination.x, destination.y, { button: 'right' });
  await timelinePage.locator('[data-context="copy"]').click();
  assert.equal(await timelinePage.locator('.grid-event').count(), 2);
  await timelinePage.mouse.click(destination.x, destination.y, { button: 'right' });
  await timelinePage.locator('[data-context="preset"]').click();
  const customPreset = timelinePage.locator('.preset-card').filter({ has: timelinePage.locator('strong', { hasText: '格子事件' }) });
  assert.equal(await customPreset.count(), 1);
  await timelinePage.waitForTimeout(350);
  await customPreset.click();
  assert.match(await timelinePage.locator('#editor-title').textContent(), /管理预设/);
  await timelinePage.locator('[name="name"]').fill('修改后的预设'); await timelinePage.locator('#save-event').click();
  assert.equal(await timelinePage.locator('.grid-event').filter({ hasText: '格子事件' }).count(), 2);
  const editedPreset = timelinePage.locator('.preset-card').filter({ hasText: '修改后的预设' });
  await timelinePage.locator('#timeline').scrollIntoViewIfNeeded(); await editedPreset.scrollIntoViewIfNeeded();
  let card = await editedPreset.boundingBox(); let drop = await coords(4, 0);
  await timelinePage.mouse.move(card.x + 30, card.y + 20); await timelinePage.mouse.down();
  await timelinePage.waitForTimeout(450);
  await timelinePage.mouse.move(drop.x, drop.y, { steps: 20 }); await timelinePage.mouse.up();
  assert.equal(await timelinePage.locator('.grid-event').count(), 3);
  assert.equal(await timelinePage.locator('[name="name"]').inputValue(), '修改后的预设');
  assert.equal(await timelinePage.locator('[name="start"]').inputValue(), '20');
  await timelinePage.waitForTimeout(350);
  // Dropping outside the timeline cancels without adding another event.
  card = await editedPreset.boundingBox();
  await timelinePage.mouse.move(card.x + 30, card.y + 20); await timelinePage.mouse.down(); await timelinePage.waitForTimeout(450);
  await timelinePage.mouse.move(10, 10, { steps: 12 }); await timelinePage.mouse.up();
  assert.equal(await timelinePage.locator('.grid-event').count(), 3);
  await timelinePage.locator('#timeline').scrollIntoViewIfNeeded(); drop = await coords(4, 0);
  await timelinePage.mouse.click(drop.x, drop.y, { button: 'right' }); await timelinePage.locator('[data-context="delete"]').click();
  assert.equal(await timelinePage.locator('.grid-event').count(), 2);
  await timelinePage.reload();
  assert.equal(await timelinePage.locator('.grid-event').count(), 2);
  assert.equal(await timelinePage.locator('.preset-card').filter({ hasText: '修改后的预设' }).count(), 1);
  await timelinePage.locator('.preset-card').filter({ hasText: '修改后的预设' }).click();
  await timelinePage.locator('#delete-preset').click();
  assert.equal(await timelinePage.locator('.grid-event').count(), 2);
  assert.equal(await timelinePage.locator('.preset-card').filter({ hasText: '修改后的预设' }).count(), 0);
  await timelinePage.evaluate(() => window.scrollTo(0, 0));
  await timelinePage.locator('#timeline-editor').screenshot({ path: root + 'artifacts/shot-timeline-editor.png' });
  assert.deepEqual(errors, []);
  await timelinePage.close();
  const managerPage = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  managerPage.on('pageerror', e => errors.push(e.message));
  await managerPage.goto(url);
  const originalSession = await managerPage.locator('.session-item.active').getAttribute('data-session');
  const menu = async id => {
    await managerPage.locator(`[data-session="${id}"]`).hover();
    await managerPage.locator(`[data-session-menu="${id}"]`).click();
  };
  await menu(originalSession); await managerPage.locator('#manager-rename').click();
  await managerPage.locator('#manager-name').fill('重命名后的会话'); await managerPage.locator('#manager-save').click();
  assert.equal(await managerPage.locator('#session-title').inputValue(), '重命名后的会话');
  await managerPage.locator('#new-group').click();
  await managerPage.locator('#manager-name').fill('关卡项目'); await managerPage.locator('#manager-save').click();
  const groupId = await managerPage.locator('[data-group-toggle]').getAttribute('data-group-toggle');
  await menu(originalSession); await managerPage.locator('#manager-move').click();
  await managerPage.locator('#manager-group').selectOption(groupId); await managerPage.locator('#manager-save').click();
  assert.equal(await managerPage.locator('.sidebar-project [data-session]').count(), 1);
  await managerPage.locator('[data-group-toggle]').click();
  assert.equal(await managerPage.locator('[data-session]').count(), 0);
  await managerPage.locator('[data-group-toggle]').click();
  await managerPage.locator('[data-new-in-project]').click();
  const otherSession = await managerPage.locator('.session-item.active').getAttribute('data-session');
  assert.equal(await managerPage.locator('.sidebar-project [data-session]').count(), 2);
  await menu(originalSession); await managerPage.locator('#manager-pin').click();
  assert.equal(await managerPage.locator('[data-session]').first().getAttribute('data-session'), originalSession);
  await managerPage.locator('[data-group-menu]').click(); await managerPage.locator('#manager-rename').click();
  await managerPage.locator('#manager-name').fill('项目新名称'); await managerPage.locator('#manager-save').click();
  await managerPage.reload();
  assert.match(await managerPage.locator('[data-group-toggle]').textContent(), /项目新名称/);
  assert.equal(await managerPage.locator('[data-session]').first().getAttribute('data-session'), originalSession);
  await managerPage.locator(`[data-session="${originalSession}"]`).click();
  await menu(originalSession); await managerPage.locator('#manager-archive').click();
  assert.equal(await managerPage.locator(`[data-session="${originalSession}"]`).count(), 0);
  assert.equal(await managerPage.locator('.session-item.active').getAttribute('data-session'), otherSession);
  await managerPage.reload();
  await managerPage.locator('#archive-toggle').click();
  assert.equal(await managerPage.locator('[data-session]').count(), 1);
  await menu(originalSession); await managerPage.locator('#manager-archive').click();
  assert.equal(await managerPage.locator('[data-session]').count(), 0);
  await managerPage.locator('#archive-toggle').click();
  await menu(originalSession); await managerPage.locator('#manager-pin').click();
  assert.equal(await managerPage.locator('.sidebar-project [data-session]').count(), 2);
  await managerPage.locator('[data-group-menu]').click();
  managerPage.once('dialog', dialog => dialog.accept()); await managerPage.locator('#manager-delete').click();
  assert.equal(await managerPage.locator('[data-group-toggle]').count(), 0);
  assert.equal(await managerPage.locator('[data-session]').count(), 2);
  await menu(originalSession);
  managerPage.once('dialog', dialog => dialog.dismiss()); await managerPage.locator('#manager-delete').click();
  assert.equal(await managerPage.locator('[data-session]').count(), 2);
  managerPage.once('dialog', dialog => dialog.accept()); await managerPage.locator('#manager-delete').click();
  assert.equal(await managerPage.locator('[data-session]').count(), 1);
  // Archiving the final visible session creates a blank workspace; the archive remains recoverable.
  await menu(otherSession); await managerPage.locator('#manager-archive').click();
  assert.equal(await managerPage.locator('[data-session]').count(), 1);
  assert.equal(await managerPage.locator('#events .empty').count(), 1);
  await managerPage.locator('#archive-toggle').click();
  await menu(otherSession); await managerPage.locator('#manager-archive').click();
  await managerPage.locator('#archive-toggle').click();
  await managerPage.locator(`[data-session="${otherSession}"]`).click();
  await menu(otherSession); managerPage.once('dialog', dialog => dialog.accept()); await managerPage.locator('#manager-delete').click();
  const finalId = await managerPage.locator('.session-item.active').getAttribute('data-session');
  await menu(finalId); managerPage.once('dialog', dialog => dialog.accept()); await managerPage.locator('#manager-delete').click();
  assert.equal(await managerPage.locator('[data-session]').count(), 1);
  assert.notEqual(await managerPage.locator('.session-item.active').getAttribute('data-session'), finalId);
  await managerPage.reload(); assert.equal(await managerPage.locator('[data-session]').count(), 1);
  assert.equal(await managerPage.locator('#events .empty').count(), 1);
  await managerPage.locator('#session-sidebar').screenshot({ path: root + 'artifacts/shot-session-management.png' });
  await managerPage.setViewportSize({ width: 390, height: 844 });
  await managerPage.locator('#sidebar-toggle').click();
  const mobileId = await managerPage.locator('.session-item.active').getAttribute('data-session');
  await managerPage.locator(`[data-session-menu="${mobileId}"]`).focus();
  await managerPage.locator(`[data-session-menu="${mobileId}"]`).press('Enter');
  assert.ok(await managerPage.locator('#session-manager').isVisible());
  await managerPage.locator('#close-session-manager').click();
  assert.deepEqual(errors, []); await managerPage.close();
  const legacy = await browser.newPage();
  await legacy.addInitScript(p => localStorage.setItem('ldtools-shot-v1', JSON.stringify(p)), { version: 1, events: scenario('repetition'), profile: PROFILES.expert, rules: DEFAULT_RULES, unit: 30 });
  await legacy.goto(url); assert.equal(await legacy.locator('#unit').inputValue(), '30');
  assert.match(await legacy.locator('#events').textContent(), /重复组合解谜/); await legacy.close();
  const migration = await browser.newPage();
  const oldProject = { version: 1, events: scenario('repetition'), profile: PROFILES.expert, rules: DEFAULT_RULES, unit: 30 };
  await migration.addInitScript(project => localStorage.setItem('ldtools-shot-sessions-v1', JSON.stringify({ version: 1, activeSessionId: 'old-session', sessions: [{ id: 'old-session', title: '旧会话', project }] })), oldProject);
  await migration.goto(url);
  assert.equal(await migration.locator('#session-title').inputValue(), '旧会话');
  assert.equal(await migration.locator('#plan-select option').count(), 1);
  assert.equal(await migration.locator('#plan-name').inputValue(), '方案 1');
  assert.equal(await migration.locator('#unit').inputValue(), '30');
  assert.match(await migration.locator('#events').textContent(), /重复组合解谜/);
  assert.equal(await migration.evaluate(() => JSON.parse(localStorage.getItem('ldtools-shot-sessions-v1')).version), 2);
  await migration.close();
  console.log('PASS: session rename/pin/archive/delete, project management, confirmation/cancel, persistence, keyboard/mobile menus, independent plans, multi-plan comparison, snapshot reload, legacy migration, existing workflows, dot-grid drafting, event move, context copy/delete/preset, long-press drag/drop, cancel, independent preset management, persistence and mobile layout');
} finally { await browser?.close(); server.kill('SIGTERM'); }
